---

- name: install dependencies for VirtualBox guest addtions
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - bzip2
    - kernel-devel
    - kernel-headers
    - gcc
    - make
    - perl

- name: Mount VirtualBox guest additions ISO
  mount:
    name: /mnt/vbox
    src: "/root/VBoxGuestAdditions.iso"
    opts: loop
    state: mounted
    fstype: iso9660

- name: Install VirtualBox guest additions
  shell: sh /mnt/vbox/VBoxLinuxAdditions.run

- name: Unmount VirtualBox guest additions ISO
  mount:
    name: /mnt/vbox
    src: "/root/VBoxGuestAdditions.iso"
    state: absent
    fstype: iso9660

- name: Delete VirtualBox guest additions ISO
  file:
    path: "/root/VBoxGuestAdditions.iso"
    state: absent
