---
- hosts: all
  become: yes
  gather_facts: no
  remote_user: vagrant

  roles:
    - mheiges.packer-centos

  tasks:
    - yum: 
        name: "{{ item }}"
        state: present
      with_items:
        - git
